- dato.config.js
- package.json
- test/index.test.js
quick update to dato, to make sure book/chapter metadata is available for paths etc on all descendants
> use books as entry for dato, pass parent meta to children

- nuxt.config.js
- package.json
Check bundle size in report.html
> bundle size check

- components/globe-component/README.md
- components/globe-component/geometry.js
- components/globe-component/globe-component.js
- dato.config.js
- nuxt.config.js
- package-lock.json
- package.json
> Globe zoom

- components/globe-component/README.md
- components/globe-component/globe-component.js
Show links between stories using flight paths.
> globe connections

- dato.config.js
- nuxt.config.js
- package-lock.json
- package.json
load object of arrays of pages by either influences, pages, themes
> Load keywords influences

- components/globe-component/GlobeComponent.vue
- components/globe-component/globe-component.js
Create viewOffset so that the center of the globe is a bit above the center of the window, while also filling the whole window.
> Globe full size

- components/card-component/CardComponent.vue
- components/card-list/CardList.vue
- dato.config.js
quick & dirty addition of number of pages to card
> add pageCount in build and on card

- layouts/default.vue
- nuxt.config.js
- package-lock.json
- package.json
> Old browsers

- components/globe-component/avatar.js
- components/globe-component/globe-component.js
- nuxt.config.js
> Fix static files

- components/typography/typography.css
- pages/narratives/_book/_chapter/_page.vue
A page should have a link to book and chapter.
> add book and chapter title

- .travis.yml
- README.md
Deploy using [travis github pages](https://docs.travis-ci.com/user/deployment/pages/) connection.
> deploy using travis instead of gh-pages package

- dato.config.js
- lib/load-data.js
- package.json
- pages/_staticPage.vue
https://issuetracker.deltares.nl/browse/WWA-73
> About us page

- components/page-body/PageBody.vue
Show the figcaption for images.
> fix(figcaption): add missing figcaption

- components/page-aside/PageAside.vue
I think this should work but I can only test it on the github server.
> fix(theme-icons): add base url

- .travis.yml
- nuxt.config.js
- test/index.test.js
Fix build (get data from localhost and not the old build from github pages).
> Travis fix

- layouts/default.vue
- nuxt.config.js
- package-lock.json
- package.json
https://issuetracker.deltares.nl/browse/WWA-178
I also made the globe async, so that three, tween etc are all loaded asynchronously
> Vendor scripts

- layouts/default.vue
Created a quick and dirty link to a static submit your story page.
This is going to be styled on friday/monday by Rick.
> quick solution for a submit link; waiting for designs

- components/globe-component/avatar.js
cherrypicked a commit from @janwillemtulp 😇
> Markers don't scale with zooming

- dato.config.js
- pages/404/index.vue
- pages/_staticPage.vue
- pages/narratives/_book/_chapter/index.vue
https://issuetracker.deltares.nl/secure/RapidBoard.jspa?rapidView=311&projectKey=WWA&view=detail&selectedIssue=WWA-188
> Wwa 188 add video to about page

- components/tag/tag.css
https://issuetracker.deltares.nl/browse/WWA-210
> refactor influences for IE

- dato.config.js
- lib/load-data.js
- nuxt.config.js
- package-lock.json
https://issuetracker.deltares.nl/browse/WWA-209
added keywords, influences, static pages, themes to nuxt generate routes.
you can check what happens when you're running it completely static by running `npm run serve` It generates all html and serves `./dist` via `http-server`
> better generate

- components/tag/tag.css
slightly better spacing on the icons for influences
> better spacing for influences icons

- components/globe-component/globe-component.js
avatars were not loaded when switching themes. This has been fixed now.
> fixed a bug where avatars were not shown when switching theme

- components/card-list/CardList.vue
- package.json
Horizontal scroll button. Fixes WWA-231
> restore horizontal scroll button

- components/card-list/CardList.vue
- nuxt.config.js
had to reset the old code, the intersectionObserver polyfill causes a stackoverflow/Hierarchy error in IE.
> fix broken ie

- package-lock.json
- package.json
Fix dependencies of the datocms  client
> fix datocms client

- nuxt.config.js
- pages/_language/events/_event/index.vue
It looks :hankey: , but it works. Adds new data and some initial styling, and it unbreaks the CI ;)
> Add event sections and speaker data

- pages/_language/events/_event/index.vue
https://issuetracker.deltares.nl/browse/WWA-394
> Add initial styling for content text block

- lib/load-data.js
- nuxt.config.js
- package-lock.json
- package.json
- router.scrollBehavior.js
Using the new [Nuxt crawler](https://nuxtjs.org/api/configuration-generate#crawler) option, reduces amount of needed code and fixes our current build problem.
> Use more Nuxt configuration defaults including new generate crawler

- components/animator/Animator.vue
- components/event-banner/EventBanner.vue
- pages/_language/events/_event/index.vue
implements motion for Event-Banner ++ refactors Animator delay implementation and clip animation
> motion for event page banner

- components/event-block/EventBlockText.vue
- components/page-body/PageBody.vue
- components/responsive-image/ResponsiveImage.vue
- components/responsive-video/ResponsiveVideo.vue
- pages/_language/events/_event/_chapter.vue
- pages/_language/events/_event/index.vue
Co-authored-by: Bas de Vleeschhouwer <bdevleeschhouwer@protonmail.com>
> Re-apply event chapter layout

- components/animator/Animator.vue
refactor Animator to have animations disabled by default >> no js version of page has visible content
> Refactor: Animator no js fallback

- components/section-blocks/SectionBlockChaptersCarousel.vue
- components/section-blocks/SectionBlockChaptersList.vue
- components/section-blocks/SectionBlockColofon.vue
- components/section-blocks/SectionBlockCredits.vue
- components/section-blocks/SectionBlockNews.vue
- components/section-blocks/SectionBlockRelatedStories.vue
- components/section-blocks/SectionBlockSchedule.vue
- components/section-blocks/SectionBlockSpeakers.vue
- components/section-blocks/SectionBlockText.vue
- components/section-blocks/SectionBlockTextMedia.vue
- components/section-blocks/SectionBlocks.vue
- dato.config.js
- pages/_language/events/_event/index.vue
- Fix build errors
- Fix webpack css imports
- Remove news item from main navigation
- Better spacing between logo's
> Fix some bugs

- components/responsive-image/ResponsiveImage.vue
Also make alt-tags for content images optional in DatoCMS.
> Fix missing alt-tags
